#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.
# Simply type the menu entries you want to add after this comment.
# Be careful not to change the 'exec tail' line above.

# Allow reboot from within grub
menuentry "Reboot" --class restart --unrestricted { reboot }

# Allow shutdown from within grub
menuentry "Shut Down" --class shutdown --unrestricted { halt }

# Enforce signature checking if --pubkey is set when generating the grub image
set check_signatures=enforce
export check_signatures

# Set grub password
set superusers="grub"
export superusers
password_pbkdf2 grub {{grub_password_hash}}

# Load french keyboard layout
insmod keylayouts
keymap /boot/grub/layouts/fr.gkb

# Load darkmatter theme
insmod png
insmod gfxterm_background
loadfont $prefix/themes/darkmatter/hackb_18.pf2
loadfont $prefix/themes/darkmatter/norwester_16.pf2
loadfont $prefix/themes/darkmatter/norwester_20.pf2
loadfont $prefix/themes/darkmatter/norwester_22.pf2
set theme=$prefix/themes/darkmatter/theme.txt
export theme
